spring.application.name=flowerecommerce
server.servlet.context-path=/api

# logging.level.root=INFO
# logging.level.com.ahmedesawy.flow=INFO


spring.jpa.hibernate.ddl-auto=update

# SQL 
spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Spring Ai
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.temperature=0.7

spring.ai.google.genai.embedding.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=1536

# spring.main.allow-bean-definition-overriding=true




# Mail
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:3000}

# Variables
jwt.secret=${JWT_SECRET}
file.upload-dir=upload_images